"""Defines font related constants used in app"""

DEFAULT_FONT = "body"
HEADLINE_FONT = "headline"

ALL_FONTS = {
    DEFAULT_FONT: "/fonts/SF-Pro-Display-Regular.ttf",
    HEADLINE_FONT: "/fonts/NewYork.ttf",
}


"""
FONT SIZES
"""
HEADLING_1_SIZE = 44
HEADLINE_2_SIZE = 30
HEADLINE_3_SIZE = 20
HEADLINE_4_SIZE = 16
BODY_1_SIZE = 11
BODY_2_SIZE = 12
SUBTITLE_1_SIZE = 12
SUBTITLE_2_SIZE = 10
BUTTON_SIZE = 12
OVERLINE_SIZE = 10
CAPTION_SIZE = 9

"""
FONT WEIGHTS
"""
BOLD_FONT = "w500"
BOLDER_FONT = "w700"
