"""Defines all text strings displayed in the app"""

APP_NAME = "Tuttle"
APP_DESCRIPTION = "Time and money management for freelancers"
APP_DESCRIPTION_LENGTHY = "Tuttle is a time and finance planning tool tailored for the requirements of freelancers."

"""splash screen strings"""
WELCOME_TITLE = "Hi, Welcome to Tuttle."
WELCOME_SUBTITLE = "Let's get you started"
GET_STARTED = "Get Started"
SPLASH_IMG_SEMANTIC_LBL = "Tuttle splash image"

""" user info """
NAME_LBL = "Name"
EMAIL_LBL = "Email"
TITLE_LBL = "Title"
TITLE_HINT = "Your freelancor title e.g. data analyst"
NAME_HINT = "Enter your name"
EMAIL_HINT = "Enter your email"
PHONE_LBL = "Phone number"
PHONE_HINT = "Include country code e.g. +49"
ADDRESS_LBL = "Your addess"
ADDRESS_HINT_OPTIONAL = "For your contracts & invoices. You can skip for now"
ID_LBL = "Id"
INVOICING_CONTACT_ID = "Invoicing Contact Id"

"""User info errors"""
MISSING_NAME_ERR = "Your name is required"
MISSING_EMAIL_ERR = "Your email is required"
MISSING_PHONE_ERR = "Your phone number is required"
TITLE_NOT_SET_ERR = (
    "You have not set your title.\nYou can use a generic one such as Freelancer"
)
PROFILE = "My Profile"

"""Side bar menu"""
PROJECTS = "Projects"
CLIENTS = "Clients"
CONTRACTS = "Contracts"
CONTACTS = "Contacts"

"""Settings"""
SETTINGS = "Settings"

"""My Projects View"""
MY_PROJECTS = "My Projects"
NO_PROJECTS_ADDED = "You have not added any projects yet."
ACTIVE = "Active"
COMPLETED = "Completed"
UPCOMING = "Upcoming"
ALL = "All"
VIEW_DETAILS = "View"
START_DATE = "Start Date"
END_DATE = "Deadline"
CLIENT_ID_LBL = "Client #"
CONTRACT_ID_LBL = "Contract #"
PROJECT_TAG = "#"
PROJECT_STATUS_LBL = "status"
SIDE_MENU_MAIN_GROUP_TITLE = "Work"
SIDE_MENU_SUB_GROUP_TITLE = "Generated"
PROJECT_LBL = "Project"
EDIT_PROJECT = "Edit Project"
MARK_AS_COMPLETE = "Mark as complete"
DELETE_PROJECT = "Delete project"
VIEW_CLIENT_LBL = "Client"
VIEW_CONTRACT_LBL = "Contract"
VIEW_CLIENT_HINT = "View client"
VIEW_CONTRACT_HINT = "view contract"
PROJECT_DESC_LBL = "Project Description"

"""DATE PICKER"""
DAY_LBL = "D"
MONTH_LBL = "M"
YEAR_LBL = "Y"


"""Create project / client / contracts"""
CREATE_PROJECT_FAILED = "Failed to create the project! Please retry"
CREATE_CLIENT_MISSING_TITLE_ERR = "The title is required"
CREATE_CLIENT_FAILED_ERR = "Saving new client failed. Please retry"
CREATE_CONTRACT_MISSING_DESCRIPTION_ERR = "The contract description is required"
CREATE_CONTRACT_FAILED_ERR = "Saving new contract failed. Please retry"
PROJECT_NOT_FOUND = "Looks like that project does not exist!"
CLIENT_NOT_FOUND = "Looks like that client does not exist!"
CONTRACT_NOT_FOUND = "Looks like that contract does not exist!"

"""Contracts List View"""
MY_CONTRACTS = "My Contracts"
NO_CONTRACTS_ADDED = "You currently have no contracts"

"""Clients List View"""
MY_CLIENTS = "My Clients"
NO_CLIENTS_ADDED = "You currently have no clients"
