"""Defines all text strings displayed in the app"""

APP_NAME = "Tuttle"
APP_DESCRIPTION = "Time and money management for freelancers"
APP_DESCRIPTION_LENGTHY = "Tuttle is a time and finance planning tool tailored for the requirements of freelancers."

"""splash screen strings"""
WELCOME_TITLE = "Hi, Welcome to Tuttle."
WELCOME_SUBTITLE = "Let's get you started"
GET_STARTED = "Get Started"
SPLASH_IMG_SEMANTIC_LBL = "Tuttle splash image"

""" user info """
NAME_LBL = "Name"
EMAIL_LBL = "Email"
TITLE_LBL = "Title"
TITLE_HINT = "Your freelancor title e.g. data analyst"
NAME_HINT = "Enter your name"
EMAIL_HINT = "Enter your email"
PHONE_LBL = "Phone number"
PHONE_HINT = "Include country code e.g. +49"
ADDRESS_LBL = "Your addess"
ADDRESS_HINT_OPTIONAL = "For your contracts & invoices. You can skip for now"

"""User info errors"""
MISSING_NAME_ERR = "Your name is required"
MISSING_EMAIL_ERR = "Your email is required"
MISSING_PHONE_ERR = "Your phone number is required"
TITLE_NOT_SET_ERR = (
    "You have not set your title.\nYou can use a generic one such as Freelancer"
)
PROFILE = "My Profile"

"""Side bar menu"""
PROJECTS = "Projects"
CLIENTS = "Clients"
CONTRACTS = "Contracts"
CONTACTS = "Contacts"

"""Settings"""
SETTINGS = "Settings"

"""My Projects View"""
MY_PROJECTS = "My Projects"
NO_PROJECTS_ADDED = "You have not added any projects yet."
ACTIVE = "Active"
COMPLETED = "Completed"
UPCOMING = "Upcoming"
ALL = "All"
VIEW_DETAILS = "View"
START_DATE = "Start Date"
END_DATE = "Deadline"
CLIENT_ID_LBL = "Client #"
CONTRACT_ID_LBL = "Contract #"
PROJECT_TAG = "#"
